# Generated by Django 3.2.18 on 2023-10-04 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20231004_1846'),
        ('users', '0003_alter_customuser_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='shops',
            field=models.ManyToManyField(blank=True, related_name='organizations_shop', to='products.Shop', verbose_name='Магазины'),
        ),
    ]
