# Generated by Django 3.2.18 on 2023-10-04 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20231004_2151'),
        ('users', '0004_organization_shops'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='orders',
            field=models.ManyToManyField(blank=True, related_name='users_order', to='orders.Order', verbose_name='Заказы'),
        ),
    ]
