# Generated by Django 3.2.18 on 2023-10-04 16:42

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0002_auto_20231004_1846'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Название')),
                ('status_type', models.CharField(max_length=256, verbose_name='Тип статуса')),
            ],
            options={
                'verbose_name': 'Статус заказа',
                'verbose_name_plural': 'Статусы заказов',
            },
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=1, verbose_name='Количество')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_products_product', to='products.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Товары из заказа',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_time', models.TimeField(default=datetime.time(21, 42, 58, 299972), verbose_name='Время доставки')),
                ('delivery_price', models.IntegerField(default=0, verbose_name='Цена доставки')),
                ('total_price', models.IntegerField(default=0, verbose_name='Итоговая цена')),
                ('total_weight', models.IntegerField(default=0, verbose_name='Суммарный вес')),
                ('fast', models.BooleanField(default=False, verbose_name='Моментальная доставка')),
                ('need_change', models.BooleanField(default=False, verbose_name='Нужен размен')),
                ('order_products', models.ManyToManyField(blank=True, related_name='orders_order_product', to='orders.OrderProduct', verbose_name='Товары')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders_order_status', to='orders.orderstatus', verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
