# Generated by Django 3.2.18 on 2023-10-04 16:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_time',
            field=models.TimeField(default=datetime.time(21, 51, 2, 326778), verbose_name='Время создания заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_time',
            field=models.TimeField(default=datetime.time(21, 51, 2, 326807), verbose_name='Время доставки'),
        ),
    ]
