# Generated by Django 3.2.18 on 2023-10-05 05:34

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20231004_2151'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderproduct',
            options={'verbose_name': 'Товар из заказа', 'verbose_name_plural': 'Товары из заказов'},
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_time',
            field=models.TimeField(default=datetime.time(10, 34, 27, 183167), verbose_name='Время доставки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_time',
            field=models.TimeField(default=datetime.time(10, 34, 27, 183140), verbose_name='Время создания заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders_order_status', to='orders.orderstatus', verbose_name='Статус'),
        ),
    ]
