# Generated by Django 3.2.18 on 2023-10-05 22:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20231005_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_time',
            field=models.TimeField(default=datetime.time(3, 41, 28, 305592), verbose_name='Время доставки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 6, 3, 41, 28, 305561), verbose_name='Время создания заказа'),
        ),
    ]
