# Generated by Django 3.2.18 on 2023-10-05 23:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20231006_0355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_time',
            field=models.TimeField(default=datetime.time(4, 21, 48, 806572), verbose_name='Время доставки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 6, 4, 21, 48, 806531), verbose_name='Время создания заказа'),
        ),
    ]
