# Generated by Django 3.2.18 on 2023-10-03 17:19

from django.db import migrations, models
import django.db.models.deletion
import products.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='ShopCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Категория магазина',
                'verbose_name_plural': 'Категории магазинов',
            },
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Название')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shops_category', to='products.shopcategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Магазин',
                'verbose_name_plural': 'Магазины',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover', models.ImageField(blank=True, null=True, upload_to=products.models.Product.get_path, verbose_name='Обложка')),
                ('name', models.CharField(max_length=512, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('compound', models.TextField(blank=True, verbose_name='Состав')),
                ('calories', models.FloatField(default=0, verbose_name='Калории')),
                ('protein', models.FloatField(default=0, verbose_name='Протеин')),
                ('fats', models.FloatField(default=0, verbose_name='Жиры')),
                ('carbohydrates', models.FloatField(default=0, verbose_name='Углеводы')),
                ('weight', models.CharField(blank=True, max_length=256, verbose_name='Вес / объём')),
                ('price', models.IntegerField(default=0, verbose_name='Цена')),
                ('amount', models.IntegerField(default=0, verbose_name='Количество')),
                ('expiration', models.TextField(verbose_name='Срок годности / условия хранения')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products_category', to='products.productcategory', verbose_name='Категория')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products_shop', to='products.shop', verbose_name='Магазин')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
    ]
