# Generated by Django 3.2.18 on 2023-10-04 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AddField(
            model_name='product',
            name='current_price',
            field=models.IntegerField(default=0, verbose_name='Текущая цена'),
        ),
        migrations.AddField(
            model_name='product',
            name='start_price',
            field=models.IntegerField(default=0, verbose_name='Начальная цена'),
        ),
    ]
