# Generated by Django 3.2.18 on 2023-10-05 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='expiration',
            field=models.TextField(default='', verbose_name='Срок годности / условия хранения'),
        ),
    ]
