# Generated by Django 3.2.18 on 2023-10-06 00:09

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to=products.models.Shop.get_path, verbose_name='Обложка'),
        ),
    ]
